package com.zenus.chatclient.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CHAT_ROOM.
 */
public class ChatRoom {

    private Long id;
    private String groupName;
    private String userName;
    private Boolean isGroup;
    private java.util.Date lastModifiedDate;

    public ChatRoom() {
    }

    public ChatRoom(Long id) {
        this.id = id;
    }

    public ChatRoom(Long id, String groupName, String userName, Boolean isGroup, java.util.Date lastModifiedDate) {
        this.id = id;
        this.groupName = groupName;
        this.userName = userName;
        this.isGroup = isGroup;
        this.lastModifiedDate = lastModifiedDate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getGroupName() {
        return groupName;
    }

    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public Boolean getIsGroup() {
        return isGroup;
    }

    public void setIsGroup(Boolean isGroup) {
        this.isGroup = isGroup;
    }

    public java.util.Date getLastModifiedDate() {
        return lastModifiedDate;
    }

    public void setLastModifiedDate(java.util.Date lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }

}
